### ISSUE TITLE
第...次失败请重新获取cookie

### ISSUE THREAD

**Issue by hero5512** [zhou-xiaojun/jd_mask#2]
把cookie各种参数填进去之后选预约报错

**Comment by hero5512** [comment]
![image](https://user-images.githubusercontent.com/10353921/75208149-b8d6bf80-57b5-11ea-999f-9d70d4a0c8a8.png)
报这个错

**Comment by zhou-xiaojun** [comment]
报这个错,很单存的就是cookie有问题了.你检查下cookie是否错误.

**Comment by hero5512** [comment]
![image](https://user-images.githubusercontent.com/10353921/75210755-ef640880-57bc-11ea-95d2-4b6ac41a53a7.png)
我是通过这种方式获取的cookie，不知道是否正确呢

**Comment by hero5512** [comment]
![image](https://user-images.githubusercontent.com/10353921/75210842-3520d100-57bd-11ea-8b90-db1b9359a115.png)
这是我的配置信息

**Comment by zhou-xiaojun** [comment]
正确的,但是在ini配置文件下,所有东西直接填进去就行了config命令读取出来的配置信息默认就是str.所以别加""会导致报错
