### ISSUE TITLE
抢购报错：

### ISSUE THREAD

**Issue by CangShui** [zhou-xiaojun/jd_mask#33]
日志：
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
商品名称:【华硕TUF-RTX3080-10G-GAMING】华硕 ASUS TUF-RTX3080-10G-GAMING 1710-1740MHz 吃鸡电竞游戏专业显卡 支持4k显示器【行情 报价 价格 评测】-京东
正在等待到达设定时间:2020-12-23 11:00:00.010000
时间到达，开始执行……
时间到达，开始执行……
时间到达，开始执行……
时间到达，开始执行……
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
访问抢购订单结算页面...
访问抢购订单结算页面...
访问抢购订单结算页面...
访问抢购订单结算页面...
时间到达，开始执行……
生成提交抢购订单所需参数...
获取秒杀初始化信息...
抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100015285144&sn=f8bfcd8b8f9f358b05db39414ae312c1&from=pc
访问商品的抢购连接...
生成提交抢购订单所需参数...
获取秒杀初始化信息...
生成提交抢购订单所需参数...
获取秒杀初始化信息...
生成提交抢购订单所需参数...
获取秒杀初始化信息...
访问抢购订单结算页面...
生成提交抢购订单所需参数...

**Comment by CangShui** [comment]
![20201223111059](https://user-images.githubusercontent.com/28698760/102955497-04aae000-4511-11eb-82f6-b4cdbb84565a.png)

这是图片

**Comment by max321** [comment]
我的抢购获取地址的响应结果是 {'type': '3', 'url': '', 'state': '11'}
这是什么问题呀。。。
